# Generated by Django 5.2 on 2025-06-12 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeereview',
            table='allemployees',
        ),
    ]
