# Generated by Django 5.2 on 2025-06-12 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0002_alter_employeereview_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerEmployeeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('row_created_date', models.DateTimeField(auto_now_add=True)),
                ('row_modified_date', models.DateTimeField(auto_now=True)),
                ('row_created_by', models.CharField(default='sysusr', max_length=50)),
                ('row_modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees_under', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Manager-Employee Mapping',
                'verbose_name_plural': 'Manager-Employee Mappings',
                'unique_together': {('manager', 'employee')},
            },
        ),
    ]
