# Generated by Django 5.2 on 2025-06-12 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0003_manageremployeemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageremployeemapping',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manageremployeemapping',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
