# Generated by Django 5.2 on 2025-06-17 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0004_alter_manageremployeemapping_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_created_date', models.DateTimeField(auto_now_add=True, db_column='created')),
                ('row_modified_date', models.DateTimeField(auto_now=True, db_column='modified')),
                ('row_created_by', models.CharField(default='sysusr', max_length=50)),
                ('row_modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('role_permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms_app.rolepermission')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role Permission',
                'verbose_name_plural': 'User Role Permissions',
                'db_table': 'user_role_permission',
            },
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
