# Generated by Django 5.2 on 2025-06-17 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0005_userrolepermission_delete_userrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_created_date', models.DateTimeField(auto_now_add=True)),
                ('row_modified_date', models.DateTimeField(auto_now=True)),
                ('row_created_by', models.CharField(default='sysusr', max_length=50)),
                ('row_modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('authority_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authority_users', to=settings.AUTH_USER_MODEL)),
                ('emp_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ManagerEmployeeMapping',
        ),
    ]
