# Generated by Django 5.2 on 2025-06-17 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0006_usergroup_delete_manageremployeemapping'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usergroup',
            table='user_groups',
        ),
    ]
