# Generated by Django 5.2 on 2025-06-17 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0007_alter_usergroup_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_created_date', models.DateTimeField(auto_now_add=True)),
                ('row_modified_date', models.DateTimeField(auto_now=True)),
                ('row_created_by', models.CharField(default='sysusr', max_length=50)),
                ('row_modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms_app.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'user_role',
            },
        ),
        migrations.DeleteModel(
            name='UserRolePermission',
        ),
    ]
