# Generated by Django 5.2 on 2025-06-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0009_employeereview_user_alter_employeereview_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeereview',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='employeereview',
            name='include',
        ),
        migrations.RemoveField(
            model_name='employeereview',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='employeereview',
            name='review_status',
        ),
        migrations.RemoveField(
            model_name='employeereview',
            name='review_type',
        ),
        migrations.RemoveField(
            model_name='employeereview',
            name='sub_unit',
        ),
        migrations.AlterModelTable(
            name='employeereview',
            table='all_employees_reviews',
        ),
    ]
