# Generated by Django 5.2 on 2025-06-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0010_remove_employeereview_employee_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeereview',
            name='review_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
