# Generated by Django 5.2 on 2025-07-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0011_alter_employeereview_review_date'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeereview',
            table='employees_reviews',
        ),
    ]
