# Generated by Django 5.2 on 2025-07-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0012_alter_employeereview_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='joined_date',
        ),
    ]
