# Generated by Django 5.2 on 2025-07-28 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0013_remove_jobdetails_joined_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('profile_photo', 'Profile Photo'), ('aadhaar', 'Aadhaar'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('voter', 'Voter ID'), ('other', 'Other')], max_length=20)),
                ('document_file', models.FileField(upload_to='personal_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_created_date', models.DateTimeField(auto_now_add=True)),
                ('row_modified_date', models.DateTimeField(auto_now=True)),
                ('row_created_by', models.CharField(default='sysusr', max_length=50)),
                ('row_modified_by', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'document_type')},
            },
        ),
    ]
