# Generated by Django 5.2 on 2025-07-28 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0014_personaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='personaldocument',
            name='document_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('voter', 'Voter ID'), ('other', 'Other')], max_length=20),
        ),
    ]
