# Generated by Django 5.2 on 2025-08-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms_app', '0015_userprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetypes',
            name='days',
            field=models.FloatField(default=0.0),
        ),
    ]
